### ISSUE TITLE
Use multiprocessing for scanning library

### ISSUE THREAD

**Issue by miek770** [cbenning/fussel#17]
Hi, it'd be nice if the site generation could be paralleled, ex.: using `multiprocessing`. I'm currently scanning a 64GB, 21877 photo library and it looks like it's going to take a while to complete.

**Comment by cbenning** [comment]
Oh interesting use-case. I've never tried it on such a big set so let me know how it turns out. Let me know how long it takes so we have a base-line to use a frame of reference? Its definitely possible to do, but I would probably try and make it configurable because the chosen thumbnails for example would be non-deterministic. Totally acceptable for many people but maybe not everyone.

Great Idea.

**Comment by cbenning** [comment]
Just a note too, for albums of that size, we might need to chunk-up the JSON data, so that things aren't slow to load? Curious how it behaves.

**Comment by miek770** [comment]
Will report back :)

**Comment by cbenning** [comment]
@miek770  I've added multiprocessing support in `v2` branch. Give it a try if still interested

**Comment by miek770** [comment]
I'm sorry for not responding earlier, and thank you for following up. I must have forgotten and moved on to another solution. Hope this won't reopen the issue..
