### ISSUE TITLE
Photo does not open with too many photos in album

### ISSUE THREAD

**Issue by rda0** [cbenning/fussel#80]
Starting with an album size of ~200 Photos, when opening a photo, the carousel view does not show the photo, just the UI controls. When clicking on `X`, the photo shortly flashes at you before switching back to the album view.

Up to ~100 photos works normal. I have not tested between 100 and 200.

I don't see any errors in the console.

Firefox: 102.0
Chrome: 103.0.5060.66
OS: Debian 11 Bullseye
Python: 3.9.2
Node: v16.15.1
Fussel: 9545f5b

**Comment by ElFishi** [comment]
+1

**Comment by swoertz** [comment]
I also ran into this issue. As a workaround I was dividing my pictures into multiple albums, which is a bit unfortunate. I had a quick look at the problem and it seems like it is also connected to the size of the viewport. I noticed that when opening the developer tools of the browser, since the viewport got much smaller. When the height of the viewport was very small the picture showed up, however when the browser window is enlarged at some point the picture is moved to the left outside of the visible area. I am not sure at this point if this is potentially a problem in `react-photo-gallery`. However I couldn't see any related issues reported upstream for the react library. Unfortunately the project doesn't seem to be very active anymore, there hasn't been any commits/releases for some years.

**Comment by cbenning** [comment]
@swoertz are you able to test this using the v2 branch? It no longer uses react-photo-gallery. I generated al album the other night with > 300 photos and it seemed to work fine. Curious if it still suffers from this.

**Comment by swoertz** [comment]
@cbenning I've tried to generate a site on the `v2` branch with the same input album where I was seeing the problem before and I 
 couldn't reproduce the issue.

**Comment by cbenning** [comment]
So @swoertz just to confirm, the issue does not appear to happen with v2?

**Comment by swoertz** [comment]
Yes, that is correct. I wasn't able to reproduce the issue on `v2`.

**Comment by cbenning** [comment]
Thank you for verifying!
